### PR TITLE
Format code with Prettier

### PR DESCRIPTION
**Pull request by MatthewStanciu**
please

### CODE REVIEW

**Review by lachlanjc — APPROVED** [review]
BIG hell YESSSSsss

**Comment by tmb** [comment]
i plan to deny this & commit directly to the repo just to spite you

=tmb
founder @ StuTech Grants ( https://grants.stutech.org )
https://tmb.sh

**Comment by MatthewStanciu** [comment]
still waiting for you to spite me

**Comment by tmb** [comment]
it uses prettier already u jerk. it just doesn't use the spacing you like

**Comment by lachlanjc** [comment]
One must also consider that @tmb is the real jerk here

**Pull request closed without merging**
